services:
  - type: web
    name: gemini-flask-backend
    env: python
    plan: free # Or your preferred plan
    region: oregon # Optional: specify a region, e.g., oregon or frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    healthCheckPath: /health # Updated to use the new health check endpoint
    envVars:
      - key: PYTHON_VERSION
        value: "3.11" # Ensure this Python version is supported by Render
      - key: GEMINI_API_KEY
        sync: false # This means you'll set it in Render's dashboard
      - key: FLASK_ENV # FLASK_APP=app is also common, but gunicorn app:app handles it.
        value: production
      - key: FRONTEND_URL # Will be Netlify URL
        value: "https://chatgeneral.netlify.app" # e.g., https://your-angular-app-name.netlify.app
      # Gunicorn worker configuration (optional, but good for performance)
      # - key: WEB_CONCURRENCY
      #   value: "3" # Number of Gunicorn workers, adjust based on plan/memory
      # - key: GUNICORN_CMD_ARGS
      #   value: "--workers=3 --threads=1" # Alternative way to set workers/threads
      # Render automatically sets PORT env var, Gunicorn uses it.
    autoDeploy: true # Optional: enable auto-deploy on git push to connected branch
